name: Build and Run Tests

on:
  push:
    branches:
      - main  # Trigger the workflow on pull request to the 'main' branch

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    permissions:
      checks: write  # Grant permission to create checks

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 16 or later

      # Step 3: Initialize Dummy npm Project and Install Dependencies
      - name: Initialize npm Project and Install Dependencies
        run: |
          # Initialize a new npm project with a dummy package.json
          echo '{"name": "dummy-project", "version": "1.0.0", "scripts": {"test": "jest"}}' > package.json
          
          # Install Jest and jest-junit for test reporting
          npm install jest jest-junit

      # Step 4: Set up Jest and Create a Dummy Test
      - name: Set up Jest and Create a Dummy Test
        run: |
          # Create a jest.config.js file for jest-junit reporter
          echo "module.exports = {
            reporters: ['default', ['jest-junit', { outputDirectory: 'build/test-results/test', outputName: 'TEST-results.xml' }]]
          };" > jest.config.js
          
          # Create a simple dummy test file that always passes
          mkdir -p tests
          echo "test('dummy test', () => { expect(true).toBe(true); });" > tests/dummy.test.js

      # Step 5: Run the Tests
      - name: Run Tests
        run: npm test -- --verbose --detectOpenHandles  # Run Jest with verbose output and detect open handles

      # Step 6: Publish Test Report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5  # Publish the JUnit test results
        if: success() || failure()  # Ensure this step runs even if tests fail
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'  # Path to the generated JUnit XML report
