name: Build and Run Tests

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Dummy Test Results
        run: |
          mkdir -p test-results
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <testsuites>
            <testsuite name="DummyTestSuite" tests="2" failures="0" errors="0">
            <testcase classname="DummyTest" name="testSuccess" time="0.001"/>
            <testcase classname="DummyTest" name="testFailure" time="0.002"/>
            </testsuite>
          </testsuites>' > test-results/TEST-dummy.xml

      - name: Verify Test Results
        run: |
          ls -R test-results
          cat test-results/TEST-dummy.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "test-results/TEST-dummy.xml"
