name: Build and Run Tests

on:
  push:
    branches:
      - main 

permissions:
   checks: write

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Create Dummy Test Results
        run: |
          mkdir -p test-results
          cat <<EOT > test-results/TEST-dummy.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <testsuite name="DummyTestSuite" tests="2" failures="1">
            <testcase classname="DummyTest" name="testSuccess" time="0.001"/>
            <testcase classname="DummyTest" name="testFailure" time="0.002">
              <failure message="Test failed">Expected true but got false</failure>
            </testcase>
          </testsuite>
          EOT
      
      - name: Verify Test Results
        run: ls -R test-results && cat test-results/TEST-dummy.xml
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'test-results/TEST-dummy.xml'
