name: Simple PDF Report

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install mocha mochawesome puppeteer --save-dev

      - name: Create test
        run: |
          mkdir -p test
          echo "const assert = require('assert');
          describe('Test', () => {
            it('should pass', () => {
              assert.strictEqual(2 + 2, 4);
            });
          });" > test/test.js

      - name: Run test and generate PDF
        run: |
          npx mocha test --reporter mochawesome --reporter-options reportDir=report,reportFilename=index
          node -e "const fs = require('fs'); const puppeteer = require('puppeteer'); (async () => {
            const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
            const page = await browser.newPage();
            await page.setContent(fs.readFileSync('report/index.html', 'utf8'));
            await page.pdf({ path: 'report/report.pdf', format: 'A4' });
            await browser.close();
          })();"

      - name: Upload PDF
        uses: actions/upload-artifact@main
        with:
          name: test-report
          path: report/report.pdf
